{
 "title": "South Korea Air Quality Tracker",
 "time": { "from": "2024-11-24T06:56:30.722Z", "to": "2024-11-24T21:32:58.626Z" },
 "panels": [
  {
   "title": "maximum and minimum pm2.5 levels in the past month",
   "type": "stat",
   "description": "show the maximum and minimum pm2.5 levels recorded in the past month.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select max(\"pm25\") as \"max pm2.5\", min(\"pm25\") as \"min pm2.5\" from \"data\" where time >= now() - 30d "
    }
   ]
  },
  {
   "title": "Daily average of all pollutants",
   "type": "gauge",
   "description": "track daily trends for all pollutants.",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm2.5\", mean(\"pm10\") as \"pm10\", mean(\"o3\") as \"ozone\", mean(\"no2\") as \"no2\", mean(\"so2\") as \"so2\", mean(\"co\") as \"co\" from \"data\" where time >= now() - 7d group by time(1d)"
    }
   ]
  },
  {
   "title": "Air Quality Levels Over Time by City",
   "type": "stat",
   "description": "Compare PM2.5 levels over time for different cities",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") AS \"pm2.5\" from \"data\" where time >= now() - 30d group by time(1d), \"city\""
    }
   ]
  },
  {
   "title": "SO2 Levels by Time of Day",
   "type": "timeseries",
   "description": "Examine SO2 pollution trends during different times of the day.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "select mean(\"so2\") as \"so2 levels\" from \"data\" where time >= now() - 7d group by time(1h)"
    }
   ]
  },
  {
   "title": "Top 5 Districts with Highest PM10 Levels",
   "type": "timeseries",
   "description": "Identify the districts with the highest recorded PM10 levels.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "select max(\"pm10\") as \"max pm10\" from \"data\" group by \"district\" order by desc limit 5"
    }
   ]
  },
  {
   "title": "Comparison of AQI and PM2.5 Over Time",
   "type": "bargauge",
   "description": "Analyze how AQI and PM2.5 levels correlate over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"aqi\") as \"average aqi\", mean(\"pm25\") as \"average pm2.5\" from \"data\" where time >= now() - 7d group by time(1d)"
    }
   ]
  },
  {
   "title": "Top 5 cities with highest pm2.5 levels",
   "type": "piechart",
   "description": "Display the top 5 cities with the highest average pm2.5 levels",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm2.5\" from \"data\" where time >= now() - 30d group by \"city\" order by desc limit 5"
    }
   ]
  },
  {
   "title": "Pollutant Contribution by City",
   "type": "histogram",
   "description": "Compare the total contribution of different pollutants from each city.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "select sum(\"pm25\") as \"pm2.5\", sum(\"pm10\") as \"pm10\", sum(\"co\") as \"co\", sum(\"no2\") as \"no2\", sum(\"so2\") as \"so2\", sum(\"o3\") as \"ozone\" from \"data\" group by \"city\""
    }
   ]
  },
  {
   "title": "Heatmap of Pollutant Concentration Across Districts",
   "type": "bargauge",
   "description": "Display average PM2.5 levels across districts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm25\" from \"data\" where time >= now() - 30d group by \"district\""
    }
   ]
  },
  {
   "title": "Ozone Levels Above Threshold",
   "type": "barchart",
   "description": "Show how many times ozone levels exceeded 100 in each city.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "select count(\"o3\") as \"ozone count\" from \"data\" where \"o3\" > 100 and time >= now() - 30d group by \"city\""
    }
   ]
  },
  {
   "title": "Geospatial Map of Air Quality (PM2.5)",
   "type": "geomap",
   "description": "Visualize PM2.5 levels across geographical locations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm25\" from \"data\" where time >= now() - 30d group by \"lat\", \"long\""
    }
   ]
  },
  {
   "title": "Temperature's Effect on PM2.5",
   "type": "timeseries",
   "description": "Explore the effect of temperature on PM2.5 levels over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "select mean(\"temperature\") as \"temp\", mean(\"pm25\") as \"pm2.5\" from \"data\" group by time(1d)"
    }
   ]
  },
  {
   "title": "\"no2\" concentration by city",
   "type": "bargauge",
   "description": "Compare average \"no2\" concentrations across cities. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"no2\") as \"no2\" from \"data\" group by \"city\""
    }
   ]
  },
  {
   "title": "Total Pollution Contribution by Month",
   "type": "bargauge",
   "description": "Visualize the total monthly contribution of each pollutant.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select sum(\"pm25\") as \"pm2.5\", sum(\"pm10\") as \"pm10\", sum(\"o3\") as \"ozone\", sum(\"co\") as \"co\", sum(\"so2\") as \"so2\", sum(\"no2\") as \"no2\" from \"data\" where time >= now() - 180d group by time(30d)"
    }
   ]
  },
  {
   "title": "Trend of PM10 Levels Over Time",
   "type": "timeseries",
   "description": "Observe trends in PM10 levels over the last 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "query": "select mean(\"pm10\") as \"pm10\" from \"data\" where time >= now() - 30d group by time(1d)"
    }
   ]
  },
  {
   "title": "Weekly Distribution of Pollutants",
   "type": "status-history",
   "description": "Analyze how pollutants vary week by week.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm2.5\", mean(\"pm10\") as \"pm10\", mean(\"o3\") as \"ozone\" from \"data\" where time >= now() - 30d group by time(7d)"
    }
   ]
  },
  {
   "title": "\"co\" levels by district",
   "type": "bargauge",
   "description": "Compare average \"co\" levels across districts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"co\") as \"co\" from \"data\" group by \"district\""
    }
   ]
  },
  {
   "title": "CO Levels Above Hazardous Threshold",
   "type": "barchart",
   "description": "Identify districts where CO levels exceeded 50.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "select count(\"co\") as \"hazardous co levels\" from \"data\" where \"co\" > 50 and time >= now() - 1d group by \"district\""
    }
   ]
  },
  {
   "title": "City-wise average of all pollutants",
   "type": "bargauge",
   "description": "Compare average levels of all pollutants across cities. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm2.5\", mean(\"pm10\") as \"pm10\", mean(\"o3\") as \"ozone\", mean(\"no2\") as \"no2\", mean(\"so2\") as \"so2\", mean(\"co\") as \"co\" from \"data\" group by \"city\""
    }
   ]
  },
  {
   "title": "Pollution levels across time by district",
   "type": "timeseries",
   "description": "Compare \"pm2.5\" levels across districts over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "select mean(\"pm25\") as \"pm2.5\" from \"data\" group by time(1d), \"district\""
    }
   ]
  },
  {
   "title": "Pollutant Comparison (PM2.5 vs. PM10)",
   "type": "piechart",
   "description": "Compare average PM2.5 and PM10 levels across cities",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select mean(\"pm25\") AS \"pm2.5\", mean(\"pm10\") as \"pm10\" from \"data\" where time >= now() - 30d group by \"city\""
    }
   ]
  }
 ]
}